// ===== 旧版(3× 放大前)原始点阵快照 —— 只读参考,勿在运行时引用 =====
// 由 tools/upscale-pix.mjs 生成:保留旧版 16px 时代的设计意图与配色分布。
export const LEGACY_PAL = {
  'P': '#f2ecdd',
  'p': '#ece5d3',
  'e': '#e2dabf',
  'E': '#d3c7a6',
  'D': '#c2b48e',
  'w': '#faf6ea',
  'k': '#2b2b2b',
  'K': '#3f4140',
  'M': '#6b6b5d',
  'm': '#8a8a7a',
  'g': '#b9b3a2',
  'r': '#b03a2e',
  'R': '#c85545',
  'q': '#8c2f27',
  'c': '#a8e2e8',
  'C': '#7fd4de',
  'u': '#5fb8c4',
  'U': '#41899b',
  'n': '#9c8455',
  'N': '#77643f',
  'o': '#c9972f',
  'O': '#e2b94e',
  'y': '#efe0b0',
  'v': '#7f8a70',
  'V': '#5c6b52',
  'J': '#4f9673',
  's': '#5d5344',
  't': '#5d6b66',
  'x': '#2b2b2b38',
  'a': '#5fb8c46e',
  'b': '#7fd4de45',
  'A': '#a8e2e822',
  'h': '#c8554566',
  'H': '#c8554536',
  'l': '#6b6b5d55',
  'L': '#6b6b5d2e',
  'j': '#c9972f5c',
  'i': '#faf6ea77'
};
export const LEGACY_PIX = {
  // 16×16
  "hero_knight_0": [
    "................",
    "......kkkk......",
    ".....kKKKKk..k..",
    ".....kKwwkwk.wk.",
    ".....kKwwwwk.wk.",
    "......kKKk...wk.",
    "...kKKKKKKKk.wk.",
    "..kKKKKKKKKKkwk.",
    "..kKKrrRRrrKkwk.",
    ".kKKKKKKKKKKkoo.",
    ".kKKKKKKKKKKkNk.",
    ".kKKKKKKKKKKkk..",
    "..kKKkKKkKKk....",
    "....kKk.kKk.....",
    "....kk...kk.....",
    "................",
  ],
  // 16×16
  "hero_knight_1": [
    "................",
    "......kkkk......",
    ".....kKKKKk..k..",
    ".....kKwwkwk.wk.",
    ".....kKwwwwk.wk.",
    "......kKKk...wk.",
    "...kKKKKKKKk.wk.",
    "..kKKKKKKKKKkwk.",
    "..kKKrrRRrrKkwk.",
    ".kKKKKKKKKKKkoo.",
    ".kKKKKKKKKKKkNk.",
    ".kKKKKKKKKKKkk..",
    "..kKKkKKkKKk....",
    "...kKk...kKk....",
    "...kk.....kk....",
    "................",
  ],
  // 16×16
  "hero_mage_0": [
    ".............w..",
    "......kkk...wmw.",
    ".....kKKKk..wmw.",
    "....kKwwkwKkN...",
    "....kKwwwwKkN...",
    "....kwwwwk..N...",
    "...kttwwwttkN...",
    "..kttwwtttttkN..",
    "..ttttttttttkN..",
    ".ttttrrRRrrttk..",
    ".tttttttttttt...",
    "..tttttttttk....",
    "...ttkrrktt.....",
    "....ktk.ktk.....",
    "....kk...kk.....",
    "................",
  ],
  // 16×16
  "hero_mage_1": [
    ".............w..",
    "......kkk...wmw.",
    ".....kKKKk..wmw.",
    "....kKwwkwKkN...",
    "....kKwwwwKkN...",
    "....kwwwwk..N...",
    "...kttwwwttkN...",
    "..kttwwtttttkN..",
    "..ttttttttttkN..",
    ".ttttrrRRrrttk..",
    ".tttttttttttt...",
    "..tttttttttk....",
    "...ttkrrktt.....",
    "...ktk...ktk....",
    "...kk.....kk....",
    "................",
  ],
  // 16×16
  "hero_ranger_0": [
    "................",
    "......kkkk......",
    "....kkMMMMkk....",
    "..kkMMMMMMMMkk..",
    ".....kKwwkwKk...",
    "...N.kKwwwwKk...",
    ".N.m.kKKKKKKk...",
    "N..m.kKKKKKKk...",
    "N..m.kKrrrKKk...",
    "N..m.kKKKKKKk...",
    ".N.m.kKKKKKKk...",
    "...m.kKKKKKKk...",
    "...N..kKKKKk....",
    ".....kKk.kKk....",
    ".....kk...kk....",
    "................",
  ],
  // 16×16
  "hero_ranger_1": [
    "................",
    "......kkkk......",
    "....kkMMMMkk....",
    "..kkMMMMMMMMkk..",
    ".....kKwwkwKk...",
    "...N.kKwwwwKk...",
    ".N.m.kKKKKKKk...",
    "N..m.kKKKKKKk...",
    "N..m.kKrrrKKk...",
    "N..m.kKKKKKKk...",
    ".N.m.kKKKKKKk...",
    "...m.kKKKKKKk...",
    "...N..kKKKKk....",
    "....kKk...kKk...",
    "....kk.....kk...",
    "................",
  ],
  // 14×14
  "slime": [
    "..............",
    ".....mmmm.....",
    "....mppppm....",
    "..mppPPppppm..",
    "..mpPpppppeM..",
    "..mpprppprpm..",
    "..mpprppprpm..",
    "..mppppppppm..",
    "..mppkkkpppm..",
    "..meppppppem..",
    "...mpmppmpm...",
    "....m..m..m...",
    ".....xxxx.....",
    "..............",
  ],
  // 14×14
  "bat": [
    "..............",
    ".k..........k.",
    ".kk........kk.",
    ".kKk..kk..kKk.",
    "kKKKkkkkkkKKKk",
    "kKKKOyKKyOKKKk",
    "kKKKOkKKOkKKKk",
    "kKKKKKooKKKKKk",
    ".kKKMKKKKMKk..",
    "..kKKKKKKKKk..",
    "...kKKKKKKk...",
    "....kKkkKk....",
    "....kk..kk....",
    "..............",
  ],
  // 16×16
  "skeleton": [
    "....kkkkkkk.....",
    "....kwwwwwwk....",
    "....kwwwwwwk.k..",
    "....kwkwwkwk.wk.",
    "....kwwwwwwk.wk.",
    "....kkkkkkkk.wk.",
    ".....kwwwwk..wk.",
    "...kwwwwwwwk.wk.",
    "...kwkwkwkwk.wk.",
    "...kwkwkwkwk.wk.",
    "....kkkkkkkkoooo",
    ".....kwwwwk..Nk.",
    ".....kKk.kKk.Nk.",
    ".....kk..kk..kk.",
    ".....xx..xx.....",
    "................",
  ],
  // 14×14
  "spider": [
    "..............",
    ".k..........k.",
    "..k..kkkk..k..",
    "...kkKrrKkk...",
    ".k..kKKKKk..k.",
    "..kkKKKKKKkk..",
    ".k.kKKKKKKk.k.",
    "k..kKMKKMKk..k",
    "k..kKKKKKKk..k",
    ".kkkKKKKKKkkk.",
    "...kKKKKKKk...",
    "..k.kkkkkk.k..",
    ".k..........k.",
    "..............",
  ],
  // 20×20
  "brute": [
    "....kkkkkkkkkkkk....",
    "...kKKKKKKKKKKKKk...",
    "...kKmmKKKKKKmmKk...",
    "...kKKrrKKKKrrKKk...",
    "...kKKKKKKKKKKKKk...",
    "...kKKkkkkkkkKKKk...",
    "....kKKKKKKKKKKk....",
    "..kMMKKKKKKKKKKMMk..",
    ".kMMKKKKrrrrKKKKMMk.",
    "kMMKkKKKrrrrKKKkKMMk",
    "kMMk.KKKKrrKKKK.kMMk",
    "kMk..kKKKKKKKKk..kMk",
    ".k...kKKKKKKKKk...k.",
    ".....kKKKkkKKKk.....",
    ".....kKKk..kKKk.....",
    ".....kKKk..kKKk.....",
    "....kMMKk..kMMKk....",
    "....kkkkk..kkkkk....",
    "..xxxxxxxxxxxxxxxx..",
    "....................",
  ],
  // 14×14
  "bomber": [
    "......hh......",
    "......kk......",
    ".....kRRk.....",
    ".....kOOk.....",
    ".....kRRk.....",
    "....kkRRkk....",
    "....kkkkkk....",
    "....kppppk....",
    "....kkppkk....",
    ".....kKKk.....",
    ".....kKKk.....",
    "....kKk.kKk...",
    "....kKk.kKk...",
    "....kk...kk...",
  ],
  // 18×18
  "turtle": [
    "..................",
    "..................",
    ".....kkkkkk.......",
    "...kkMMMMMMkk.....",
    "..kMmmMMMMMMMk....",
    ".kMMmkkMMkkMMk....",
    ".kMMkkMMkkMMkkttt.",
    ".kMmMkkMMkkMMktkt.",
    ".kMMkkMMkkMMkkttt.",
    ".kMMkkMMkkMMkkttk.",
    "..kMMkkMMkkMMktt..",
    "...kkMMMMMMkkk....",
    "....kkkkkkkkkk....",
    "...kMMk..kMMk.....",
    "...kmmk..kmmk.....",
    "...kkk....kkk.....",
    "...xx......xx.....",
    "..................",
  ],
  // 12×12
  "wisp": [
    "....uu......",
    "...uuuuu....",
    ".bbCcccCbb..",
    "bCccwcwccCb.",
    "bCcwwuwwcCb.",
    "bCccwcwccCb.",
    ".bbCcccCbb..",
    "...uuuuu....",
    "...buuub....",
    "....bAb.....",
    "............",
    "............",
  ],
  // 20×20
  "reaper": [
    "........kkkkkk......",
    ".......kwwwwwwk.....",
    ".......kwrwrrwk.....",
    ".......kwwwwwwk.....",
    ".......kwwwwwwk.....",
    ".....kkkwwwwwwkkk...",
    "...kkwwwwwwwwwwwwkk.",
    "....kwwkwwwwkwwk....",
    "....kwwwwwwwwwwk....",
    ".....kkwwkkwwkk.....",
    "....kKKkkRRkkKKk....",
    "...kKKKKkRRkKKKKk...",
    "...kKKKKkRRkKKKKk...",
    "...kKKKKkrrkKKKKk...",
    "..kKKKKKKkkKKKKKKk..",
    "..kKKKKKKKKKKKKKKk..",
    "..kKKKKKKKKKKKKKKk..",
    "..kKkKKKkKKKkKKKkk..",
    "..kk.kkk.kk.kk......",
    "....xx.xx.xx.xx.....",
  ],
  // 40×40
  "boss_golem": [
    "........................................",
    "........................................",
    "...................kk...................",
    "................kkkggkkk................",
    "..............kkggggggggkk..............",
    "............kkggggmmmmmgggkk............",
    "...........kMMMMMMmmmmMMMMMMk...........",
    "...........kMkkkkkmmmmkkkkkMk...........",
    "...........kgkkcckmmmmkcckkgk...........",
    "...........kgkkkkkmmmmkkkkkmk...........",
    "...........kggmkmmmmmmmmmmmmk...........",
    ".....kkk...kggkmmmmmmmmmmmmmk...kkk.....",
    "....kgggkk.kggmmmmkmmkmmmVVVk.kkgggk....",
    "...kggggggkkgggmmkkkkkkmmmmgkkggggggk...",
    "..kggmmgggkgggggmmmmmmmmmmgggkgggmmggk..",
    "..kgmmmmgvvvvgmmgmmmmmmmmmmmggggmmmmgk..",
    "..kmmmmmmvvvvmmmmmmggmmmmmmmmggmmmmmmk..",
    ".kgmmmmmmgggmmmmmmmmmmmmmmmmmggmmmmmmgk.",
    ".kgmmmmmkggmmmmmmmmmmmmmmmmmmggmmmmmmgk.",
    ".kmmmmmmmkgmmmmmmmmmmmmmmmmmmgmmmmmmmmk.",
    ".kmmmmmmmkgmmmmmmmmmmmmmmmmmmgmmmmmmmmk.",
    ".kmmmmmmmmkmmmmmmmmmmmmmmmmmmgkmmmmmmmk.",
    ".kmmmmmmmmgkmmmmmmkkkkmmmmmmmkmmmmmmmmk.",
    ".kmmmmmmmmgkmmmmkkaaaakkmmmmmkmmmmmmmmk.",
    "..kmmmmmmggmkmmmkaccccakmmmmkggmmmmmmk..",
    "..kmmmmmmggmmmmkkaccwcakkmmmkggmmmmmmk..",
    "..kmmmmmmgmmmmmkkaccccakkmmkmmgmmmmmmk..",
    "...kmgggggmmmmmmkaccccakmmmmVVVggggmk...",
    "..kggggggggmmmmmkkaaaakkmmmmVVVggggggk..",
    ".kMMMMMMmgggmmmmmmkkkkmmmmmmVVVMMMMMMgk.",
    ".kMMMMMMmmgggmvmmmmmmmmmmmmmggmMMMMMMgk.",
    ".kmmmmmmmmgggvvvmmmmmmmmmmmmggmmmmmmmmk.",
    ".kmmmmmmmmggkmvgmmmmmmmmmmMkggmmmmmmmmk.",
    ".kmmmmmmmmggMmmmmggmmmmMmmmMggmmmmmmmmk.",
    ".kgmmmmmmmgkMmmmmmMkkMmmkmmMkgmmmmmmmgk.",
    "..kmmmmmmggkMMMMMMMkkMMMMkkMkggmmmmmmk..",
    "...kkggggkkkMMMMMMMkkMMMMMkkkkkggggkk...",
    ".....kkkk..kMMMMMMMkkMMMMMMMkk.kkkk.....",
    "........xxxxxxxxxxxxxxxxxxxxxxxx........",
    "........................................",
  ],
  // 56×56
  "boss_overlord": [
    "......................kkkkkkkkkkkk......................",
    ".....................kkkkkkkkkkkkkk.....................",
    ".....................kwwwwwwwwwwwwk.....................",
    ".....................kwwrrrwwwwwwwk.....................",
    ".....................kwwrrrwwwwwwwk.....................",
    ".....................kwwrwrwwwwwwwk.....................",
    ".....................kwwrrrwwwwwwwk.....................",
    ".....................kwwrrrwwwwwwwk.....................",
    "....................kkwwwwwwwwwwwwkk....................",
    "...................kpkkkkkkkkkkkkkkpk...................",
    "...................kpkkkkkkkkkkkkkkpk...................",
    "...................kpkkkkkwwwwkkkkkpk...................",
    "...................kpkkkkkwwwwkkkkkpk...................",
    "...................krkwRrwwwwwwRrkkpk...................",
    "...................kpkwrrwwwwwwrrkkpk...................",
    "...................kpkwwwwwwwwwwwkkrk...................",
    ".............kkkk..kpkwwwwwwwwwwwkkpk..kkkk.............",
    "...........kkKKKKkkkpkkwwkkkkkkwkkkpkkkKKKKkk...........",
    ".........kkKmmmmmmKkk.kkwwkwwkwkkk.kkKmmmmmmKkk.........",
    "........kKKkkkkkkKKKKkkkkkwwwkkkkkkKKKKkkkkkkKKk........",
    "........kKkkkkkkkkKKKKKKKKKkkKKKKKKKKKkkkkkkkkKk........",
    "........kkkkkkkkkkkKKKKKKKKKKKKKKKKKKkkkkkkkkkkk........",
    "........kkkkkkkkkkkKKKKKKKKKKKKKKKKKKkkkkkkkkkkk........",
    "........kkkkkkkkkkkKKKKKKKrrrrKKKKKKKkkkkkkkkkkk........",
    "........kkkkkkkkkkkKKKKKKrrRRrrKKKKKKkkkkkkkkkkk........",
    ".........kkkkkkkkKKKKKMKKrRRRRrKKKKKKKKkkkkkkkk.........",
    "...........kKKKKKKKKKMMMKrRyRRrKKKKKKKKKKKKKk...........",
    "...........kKkkkkKKKKMMMKrRRRRrKKMKKKKKkkkkKk...........",
    "..........kkKkkkkKKKKMMKKrRRRRrKMMMKKKKkkkkKkk..........",
    "..........kkKkkkkKKKKMMKKrrRRrrKKMMKKKKkkkkKkk..........",
    "..........kkKkkkkKKRRrrrrrrrrrrrrrrrKKKkkkkKkk..........",
    ".........kkkkkkkkKKRRrrrrrrrrrrrrrrrKKKkkkkkkkk.........",
    ".........kkKkkkkKKKRRMMKKMMKKKKKKMMKKKKKkkkkKkk.........",
    "........kkkKkkkkKKKRRMMKKMMKKKKKKMMKKKKKkkkkKkkk........",
    "........kkkKkkkkKKKKMMMKKMMKKKKKKMMKKKKKkkkkKkkk........",
    ".......kkkKKkkkkKKKKMMKKKMMKKKKKKMMMKKKKkkkkKKkkk.......",
    ".......kkkKKkkkkKKKKMMKKKMMKKKKKKKMMKKKKkkkkKKkkk.......",
    "......kkkKKKkkkkKKKKMMKKKMMKKKKKKKMMKKKKkkkkKKKkkk......",
    "......kkkKKKkkkKKKKKMMKKKMMKKKKKKKMMKKKKKkkkKKKkkk......",
    "......kkkKKkkkkkKKKMMMKKKMMKKKKKKKMMKKKKkkkkkKKkkk......",
    ".....kkkKKKkkkkkKKKMMMKKKMMKKKKKKKMMKKKKkkkkkKKKkkk.....",
    ".....kkkKKKkkkkkKKKKMKKKKMKKKKKKKKMMKKKKkkkkkKKKkkk.....",
    "....kkkKKKKkkkkkKKKKKKKKKMKKKKKKKKMMMKKKkkkkkKKKKkkk....",
    "....kkkKKKKkkkkkKKKKKKKKKMKKKKKKKKKMKKKKkkkkkKKKKkkk....",
    "...kkkKKKKkKKkKKKKkKKKKkKMkKKKKkKKKKkKKkKKKKkKKKKkkkk...",
    "...kkkKkKKKKkKKkKKKKkKKKKkKKkKKKKkKKKKkKKkKKKKkKKKkkk...",
    "..kkkKKKKkKKKKkKKkKKKKKKKKKkKKkKKKKKKKKKkKKkKKKKkKKkkk..",
    "...kkKkKKKKkKKKKkKKkKKKKKKKKKkKKKKKKKkKKKKkKKkKKKKkkkk..",
    "....kk.kkkk.kkkk.kkkKKKKKkkkk.kKKKKKk.kkkk.kk.kkkk.kk...",
    "...................kKKKKKk....kKKKKKk...................",
    "...................kkkkkkk....kkkkkkk...................",
    "...................kkkkkkk....kkkkkkk...................",
    "...................kkkkkkk....kkkkkkk...................",
    "...................kkkkkkk....kkkkkkk...................",
    "..............xxxxxxxxxxxxxxxxxxxxxxxxxxxx..............",
    "........................................................",
  ],
  // 10×10
  "w_knife": [
    "..........",
    "......cc..",
    ".....cCCb.",
    "..ccCcCCb.",
    ".cCcwwCCb.",
    "..ccCcCCb.",
    "......cCb.",
    ".......cb.",
    "..........",
    "..........",
  ],
  // 8×8
  "w_bolt": [
    "........",
    "....kkk.",
    "...kKKKk",
    ".rpkkCKk",
    ".rpkkKKk",
    "...kKKk.",
    "....kKk.",
    ".....kk.",
  ],
  // 12×8
  "w_arrow": [
    "............",
    "vv......kk..",
    ".vv....kwwk.",
    "..vvvvvkwwkk",
    "..VVVVVkwwkk",
    ".vv....kwwk.",
    "vv......kk..",
    "............",
  ],
  // 10×10
  "w_orb": [
    "...kkkk...",
    "..kmmmmk..",
    ".kmPmmmmk.",
    ".kmPmmMMk.",
    "kmmmmmmMMk",
    "kmmmmmMMKk",
    ".kmmmMMKk.",
    ".kmMMKKk..",
    "..kkkkk...",
    "..........",
  ],
  // 12×12
  "w_fireball": [
    "............",
    "....hh......",
    "...hRRh.....",
    "..hRORRh....",
    "..ROOORRk...",
    ".kROOORRk...",
    ".kRROORRk...",
    "..kRRRRk....",
    "..kqRRqk....",
    "...kqqk.....",
    "....qq......",
    "............",
  ],
  // 12×12
  "w_boomerang": [
    "....kkkk....",
    "..kMMMMMMk..",
    ".kMMMMMMMMk.",
    "kkMMm.kkkk..",
    "kkMm........",
    "kkM.........",
    "kkM.........",
    "kkMm........",
    "kkMMm.kkkk..",
    ".kMMMMMMMMk.",
    "..kMMMMMMk..",
    "....kkkk....",
  ],
  // 10×10
  "w_flask": [
    "...kkk....",
    "...kNk....",
    "...knk....",
    "..kPnnk...",
    "...knNk...",
    "..knnnnk..",
    ".knnKKnnk.",
    ".knKKKnnk.",
    ".knKKKKnk.",
    "..kkkkkk..",
  ],
  // 16×16
  "w_shield": [
    "................",
    ".....kkkkkk.....",
    "...kkMMMMMMkk...",
    "..kkMMkkkkMMkk..",
    ".kkMMk....kMMkk.",
    ".kMMk......kMMk.",
    "kkMMk......kMMkk",
    "kkMk........kMkk",
    "kkMk........kMkk",
    "kkMMk......kMMkk",
    ".kMMk......kMMk.",
    ".kkMMk....kMMkk.",
    "..kkMMkkkkMMkk..",
    "...kkMMMMMMkk...",
    ".....kkkkkk.....",
    "................",
  ],
  // 8×28
  "lightning_v": [
    ".pppppp.",
    ".pRrrRp.",
    ".pppppp.",
    ".ppCwpp.",
    ".ppCwpp.",
    ".ppCwpp.",
    ".ppCwpp.",
    ".pCwpp..",
    ".pCwpp..",
    ".pCwpp..",
    ".pCwpp..",
    ".ppCwpp.",
    ".ppCwpp.",
    ".ppCwpp.",
    ".ppCwpp.",
    ".pCwpp..",
    ".pCwpp..",
    ".pCwpp..",
    ".pCwpp..",
    ".ppCwpp.",
    ".ppCwpp.",
    ".ppCwpp.",
    ".ppCwpp.",
    ".pCwpp..",
    ".pCwpp..",
    ".pCwpp..",
    ".pCwpp..",
    ".pppppp.",
  ],
  // 48×48
  "zone_holy": [
    "................................................",
    "...................LLLLL.L......................",
    "................L.LLLLLLL.LL.LL.................",
    "..............LL.LllllllLlllllL..L..............",
    "............LLLlllllll....lllllllLL.............",
    "...........L.lllLl............LllllL.L..........",
    ".........LLLlll..................lLlL...........",
    "........L.lll......................lll.L........",
    "........Llll..........llll..........lLLLL.......",
    ".......LllL.......llllllLllLlL.......lLlLL......",
    "......Llll......LllllL....lLllll......LllL......",
    ".....LLll......llLl..........lLll......llLL.....",
    ".....LlL.....llll..............LllL.....ll.L....",
    "....Lll.....LLl.....L.L.LLLL.....lLl.....llL....",
    "...LLll.....lL....L.LLL..LL.LL....ll.....LlLL...",
    "...Lll.....ll....LLL........LLL....Ll.....lLL...",
    "..LLlL....lLl...LL.................Lll....ll....",
    "..LLll....ll...LL...............L...LL....llLL..",
    "..LlL....Lll...L.................L..lll....LlL..",
    ".L.lL....ll...L.......LLLL......LL...ll....LlLL.",
    "..Lll....lL..LL.....LLLLLLLL.....LL..Ll....Ll.L.",
    "...Ll....lL...L.....LLLLLLLL.....LL..ll....llLL.",
    "..LL....LL....L....LLLLLLLLLL....LL...lL....lLL.",
    ".L.l....lL...L.....LLLLLLLLLL.........lL....l.L.",
    ".LLl....lL...L.....LLLLLLLLLL.....L...ll....l...",
    ".L.l....ll...LL....LLLLLLLLLL....LL...ll....lL..",
    ".LLll....lL..L......LLLLLLLL.........lL....lLLL.",
    ".L.ll....ll..LL.....LLLLLLLL......L..lL....ll.L.",
    "..Lll....Ll...LL......LLLL......LL...ll....llLL.",
    "...ll....Lll..LL................LL..lLl....llL..",
    "..LLLl....ll....L..............LL...lL....llLL..",
    "..L.ll....Lll...LL.............L...lll....ll....",
    "....lL.....Ll......L.........LL....Ll.....llL...",
    "....LlL.....ll....LL.LL..LLLLL....ll.....llLL...",
    ".....ll.....LlL.....LLL.LLLL.....lll.....llL....",
    "....L.ll.....llll..............LllL.....llLL....",
    ".....LLll......Llll..........lllL......lLLL.....",
    ".....LLlll......LllLll....llllll......Lll.......",
    ".......Llll.......lLllLllllLLl.......lllL.......",
    "........Llll..........lllL..........lll.........",
    "........L.lll......................lllLL........",
    "............lLl..................lllLLL.........",
    "............LLllLl............lllllLL...........",
    ".............LLllllLll....lLLllllLLL............",
    ".................LllllllllllLlLLLL..............",
    "................L.L.L.L.LLLL.L.L................",
    "....................L......LL...................",
    "................................................",
  ],
  // 8×8
  "gem_b": [
    "...cc...",
    "..bCc...",
    ".bcCwc..",
    ".cCwCCb.",
    ".bCCCub.",
    "..uCCu..",
    "...uu...",
    "........",
  ],
  // 8×8
  "gem_g": [
    "...vv...",
    "..bVv...",
    ".bvVwv..",
    ".vVwJJb.",
    ".bJJJvb.",
    "..JJJv..",
    "...JJ...",
    "........",
  ],
  // 8×8
  "gem_r": [
    "...RR...",
    "..bRh...",
    ".bhRwO..",
    ".hRwOOb.",
    ".bOOOrb.",
    "..rrrq..",
    "...rq...",
    "........",
  ],
  // 8×8
  "coin": [
    ".kkkkkk.",
    "kOooooOk",
    "kOokkoOk",
    "kookkook",
    "kNokkoNk",
    "kNokkoNk",
    "kNooooNk",
    ".kkkkkk.",
  ],
  // 12×12
  "meat": [
    "............",
    "...kkkk.....",
    "..kwwwwk....",
    ".kwPPwwwwk..",
    ".kwPwwwwk...",
    ".kwwwwwwek..",
    ".kwwwwwwwk..",
    ".kwwwwwwk...",
    "..kwwwwk....",
    "...kkkkk....",
    "...xxxx.....",
    "............",
  ],
  // 12×12
  "magnet": [
    ".....kk.....",
    "....kOOk....",
    "...kOOOOk...",
    "...kOOOOk...",
    "..kOOOOOOk..",
    "..kOyOOyOk..",
    "..kOOOOOOk..",
    "..kkkkkkkk..",
    "...kOOOOk...",
    "....krrk....",
    "....krrk....",
    "............",
  ],
  // 16×16
  "chest": [
    "................",
    "..kkkkkkkkkkkk..",
    ".kNNNNNNNNNNNNk.",
    ".kNnnnnnnnnnnNk.",
    ".kNnnnnnnnnnnNk.",
    ".kkkkkkkkkkkkkk.",
    ".kNNNNNNNNNNNNk.",
    ".kNnnnOOOOnnnNk.",
    ".kNnnnOOnnnnnNk.",
    ".kNnnnOOnnnnnNk.",
    ".kNnnnnnnnnnnNk.",
    ".kNnnnnnnnnnnNk.",
    ".kkkkkkkkkkkkkk.",
    ".xxxxxxxxxxxxxx.",
    "................",
    "................",
  ],
  // 16×16
  "tile_grass_0": [
    "pppppppppppppppp",
    "pppPpppppppppppp",
    "pppppppppppppppp",
    "pppppppPpppppppp",
    "pppppppppppepppp",
    "pppppppppppppppp",
    "ppPppppppppppppp",
    "pppppppppppppppp",
    "pppppppppPpppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "ppeppppppppppppp",
    "pppppppppppppPpp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
  ],
  // 16×16
  "tile_grass_1": [
    "pppppppppppppppp",
    "pppppppppppppppp",
    "ppPppppppppppppp",
    "pppppppppppppppp",
    "ppppppppppppppep",
    "pppppppPpppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "ppppppppppppPppp",
    "pppppppppppppppp",
    "pepppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppPpppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
  ],
  // 16×16
  "tile_grass_2": [
    "pppppppppppppppp",
    "pppppppepppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "ppppppppppppPppp",
    "ppPppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppPpppppppppp",
    "pppppppppppepppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
  ],
  // 16×16
  "tile_dirt": [
    "EEEEEEEEEEEEEEEE",
    "EEEDEEEEEEEEEEEE",
    "EEEEEEEEEDEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEDEEEEEEEEEEEEE",
    "EEEEEEEEEEEEDEEE",
    "EEEEEDEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EDEEEEEEEDEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEEDEEEEEEEEE",
    "EEEEEEEEEEEEEEEE",
    "EEEEEDDEEEEEDEEE",
    "EEEEEEEEEEDEEEEE",
    "EEEEEEEEEEEEEEEE",
  ],
  // 16×16
  "dec_rock": [
    "................",
    "................",
    "................",
    "................",
    "......MMMM......",
    ".....kMmgmM.....",
    "....kMmgmmgM....",
    "...kMmgmmmgmM...",
    "...kMmmgmmmmM...",
    "..kMmgmmmmgmmM..",
    "..kMmmmmmmgmmM..",
    ".kMmgmmmmmmmgmM.",
    ".MMMMMMMMMMMMMM.",
    "..xx........xx..",
    "................",
    "................",
  ],
  // 16×16
  "dec_flower": [
    "................",
    ".............s..",
    "............s...",
    "...........s....",
    "...RR.....s.....",
    "..RORs...s......",
    "...RR.....s.....",
    "..........s.....",
    ".........s......",
    "....s..RRR......",
    ".......ROR......",
    "........RR......",
    "..R.............",
    "................",
    "................",
    "................",
  ],
  // 16×16
  "dec_bones": [
    ".......k........",
    ".......s........",
    "....k..s........",
    "....ks.s........",
    ".....kss....k...",
    "......ss...k....",
    "......ss..ks....",
    ".......ssks.....",
    ".......kss......",
    "........ss......",
    "........ss......",
    ".......kss......",
    "......ss.kk.....",
    "................",
    "................",
    "................",
  ],
  // 16×16
  "dec_stump": [
    "..v.....v.......",
    ".vv....vvv......",
    "..k.....k.......",
    "..k..v..k.......",
    "..k.....k....v..",
    "..V.....V.......",
    ".vk.....k..vv...",
    "..k.v...k.......",
    "..k.....k..v....",
    "..V.....V.......",
    ".vk.....kv......",
    "..k.....k.......",
    "..k.....k.......",
    "..V.....V.......",
    ".xx.....xx......",
    "................",
  ],
  // 16×16
  "p_might": [
    "................",
    "................",
    "...kkkkkkkkkk...",
    "..kNNNNNNNNNNk..",
    "..kNwwwwwwwwNk..",
    "..kNwkkkkkkwNk..",
    "..kNwkkwwkkwNk..",
    "..kNwkkwwkkwNk..",
    "..kNwkkkkkkwNk..",
    "..kNwwwwrwwwNk..",
    "..kNPPPPPPPPNk..",
    "..kkkkkkkkkkkk..",
    "..xxxxxxxxxx....",
    "................",
    "................",
    "................",
  ],
  // 16×16
  "p_cd": [
    "................",
    "..kkkkkkkkkk....",
    "..kwwwwwwwwk....",
    "..kwOOOOOOwk....",
    "...kwkOOOkwk....",
    "....kwkOkwk.....",
    ".....kwkwk......",
    "......kwk.......",
    "......kwk.......",
    ".....kwkwk......",
    "....kwOOOwk.....",
    "...kwkOOOOkwk...",
    "..kwkkkkkkkwk...",
    "..kwwwwwwwwwk...",
    "..kkkkkkkkkkk...",
    "................",
  ],
  // 16×16
  "p_speed": [
    "................",
    "................",
    "................",
    "....kOk.kOk.....",
    ".....kOkkOk.....",
    ".....kkOOkk.....",
    "..kkkkkkkkkk....",
    "..kononononk....",
    "..kOnOnOnOnk....",
    "..kononononk....",
    "..kkkkkkkkkk....",
    "...xxxxxxxx.....",
    "................",
    "................",
    "................",
    "................",
  ],
  // 16×16
  "p_hp": [
    "................",
    "................",
    "................",
    ".....hhhh.......",
    "....hRRRRh......",
    "...hRROORRh.....",
    "...hROwOORh.....",
    "...hROOORRh.....",
    "....hRRRRh......",
    ".....hhhh.......",
    ".....xxxx.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  // 16×16
  "p_magnet": [
    "................",
    "................",
    ".....kkk........",
    "....kkOkk.......",
    "....kOOOk.......",
    "...kOOOOOk......",
    "..kOOOOOOOk.....",
    "..kOyOOOyOk.....",
    "..kOOOOOOOk.....",
    "..kkkkkkkkk.....",
    "...kOOOOOk......",
    "....krrrk.......",
    "....krrrk.......",
    ".....xxx........",
    "................",
    "................",
  ],
  // 16×16
  "p_xp": [
    "................",
    "................",
    "..kN........Nk..",
    "..kNppppppppNk..",
    "..kNpPPpPPppNk..",
    "..kNppppppppNk..",
    "..kNpPPpPPppNk..",
    "..kNppppppppNk..",
    "..kNpPPpPpppNk..",
    "..kNppppppppNk..",
    "..kN........Nk..",
    "..kkk......kkk..",
    "...xxxxxxxx.....",
    "................",
    "................",
    "................",
  ],
  // 16×16
  "p_gold": [
    "................",
    "................",
    "......kk........",
    ".....kNNk.......",
    "....kNnnNk......",
    "...kNnnnnNk.....",
    "..kNnnnnnnNk....",
    "..kNnnOOnnNk....",
    "..kNnnOOOnNk....",
    "..kNnnnOOnNk....",
    "..kNnnnnnnNk....",
    "...kNnnnnNk.....",
    "....kkkkkk......",
    ".....xxxx.......",
    "................",
    "................",
  ],
  // 16×16
  "p_armor": [
    "................",
    ".kkkk....kkkk...",
    ".kMMkkkkkkkkMMk.",
    ".kMMkKKKKKKkMMk.",
    ".kMMkKMMMMKkMMk.",
    ".kMMkKMOOMKkMMk.",
    ".kMMkKMOOMKkMMk.",
    ".kMMkKKKKKKkMMk.",
    ".kMMkKKKKKKkMMk.",
    ".kMkkKKKKKKkkMk.",
    ".kkkkkkkkkkkkkk.",
    "...xxxxx.xxxx...",
    "................",
    "................",
    "................",
    "................",
  ],
  // 16×16
  "p_crit": [
    "................",
    ".......k........",
    "....k..k..k.....",
    ".....kkkkk......",
    "...kkwwwwwkk....",
    "..kwwwwwwwwk....",
    ".kwwwrrrrwwwwk..",
    ".kwwwrkkrrwwwk..",
    "..kwwwrrwwwk....",
    "...kkwwwwkk.....",
    ".....kkkkk......",
    "....k..k..k.....",
    ".......k........",
    "................",
    "................",
    "................",
  ],
  // 16×16
  "w_knife_evo": [
    ".......kwk......",
    ".......kwk......",
    "..c....kwk....c.",
    "..Cc...kwk...Cc.",
    "...Cc..kwk..Cc..",
    "....Cc.kwk.Cc...",
    ".....CckwkCC....",
    ".....ooOoooo....",
    "......kNk.......",
    "......kNk.......",
    "......kkk.......",
    "..C..........C..",
    "...Cc......Cc...",
    "....Cc....Cc....",
    ".....Cc..Cc.....",
    "......CCCC......",
  ],
  // 16×16
  "w_wand_evo": [
    ".......kk.......",
    "....kkkkkkkk....",
    "..kkkkkkkkkkk...",
    "..kkk......c....",
    ".kkkk...........",
    ".kk..MMMMMM.....",
    ".kk.MM....MM....",
    "kkk.MM....MM....",
    "kkk.MM....MM....",
    "kkk.MM....MM.kkk",
    ".kk.....CMM..kk.",
    ".kkk....MM.kkk..",
    "..kk........kk..",
    "..kkkkkkkkkkkk..",
    "....kkkkkkkk....",
    ".......kk.......",
  ],
  // 18×8
  "w_bow_evo": [
    "..................",
    "............hkkkk.",
    ".OO.......kkRRRRk.",
    "kOOrRrrrrrRROOwRk.",
    "kOOrRrrrrrRROOwRk.",
    ".OO.......kkRRRRk.",
    "............hkkkk.",
    "..................",
  ],
  // 16×16
  "w_orb_evo": [
    "................",
    ".......MM.......",
    "......MPPM......",
    ".......MM.......",
    "..MM........MM..",
    "..MMkmmmmmmkMM..",
    "....kmPmmmmk....",
    "....kmPmmMMk....",
    "....kmmmmMKk....",
    ".....kkkkkk.....",
    "..MM........MM..",
    ".......MM.......",
    "......MKKM......",
    ".......MM.......",
    "................",
    "................",
  ],
  // 12×32
  "w_lightning_evo": [
    "..pppppppp..",
    "..pRrrrrRp..",
    "..pppppppp..",
    "..ppCwpCup..",
    "..ppcwpcup..",
    "..ppCwpCup..",
    "..ppcwpcup..",
    "..ppCwpCup..",
    "..ppCwpCup..",
    "..pCwppCup..",
    "..pcwppcup..",
    "..pCwppCup..",
    "..pcwppcup..",
    "..pCwppCup..",
    "..pCwppCup..",
    "..ppCwpCup..",
    "..ppcwpcup..",
    "..ppCwpCup..",
    "..ppcwpcup..",
    "..pCwppCup..",
    "..pcwppcup..",
    "..pCwppCup..",
    "..pCwppCup..",
    "..pCwppCup..",
    "..pCwppCup..",
    "..pCwppCup..",
    "..pCwppCup..",
    "..pCwppCup..",
    "..pCwppCup..",
    "..pCwppCup..",
    "..pppppppp..",
    "....orOo....",
  ],
  // 16×16
  "w_fireball_evo": [
    "......hh........",
    ".....hRRh.......",
    "....hROORh......",
    "...hROOOORh.....",
    "..hROOwOORh.....",
    "..kROwwOORk.....",
    ".kRROOOOORRk....",
    ".kRROOOOORRk....",
    ".kqRROOORRqk....",
    "..kqqRRRRqqk....",
    "...kqqqqqqk.....",
    "....kkqqqkk.....",
    "......kqk.......",
    ".......k........",
    "................",
    "................",
  ],
  // 16×16
  "w_boomerang_evo": [
    ".......jj.......",
    "...jOOOOOOOOj...",
    "..jOOOOOOOOOOj..",
    ".jOOkkkkkkkkOOj.",
    ".jOOkkkk........",
    ".jOOkkm.........",
    ".jOOk...........",
    ".jOOk...........",
    ".jOOkm..........",
    ".jOOkkkk........",
    ".jOOkkkkkkkkOOj.",
    "..jOOOOOOOOOOj..",
    "...jOOOOOOOOj...",
    ".......jj.......",
    "................",
    "................",
  ],
  // 24×24
  "w_holy_evo": [
    ".......kkMkMkkkkk.......",
    ".....MkMkkk.lkMkMkk.....",
    "....kkk.ll.ll.ll.kkM....",
    "...kkk.l........llkkk...",
    "..MkM.l...........lkMk..",
    ".kkk.....mMMMMM.....kkk.",
    ".kk.l..MMM....mMM..llMk.",
    "kM.l..MM........Mm...lkk",
    "kkl...m..ll...l..M...lMk",
    "Mkl..MM.......ll.Mm...kk",
    "kk...m..l..kk..l..M..lkM",
    "k.l..M....kkkk.l..M..l.k",
    "kll..M..l.kkkk....M...lk",
    "kk...M..l..kk..l..M..lMk",
    "Mkl..MM.ll.......Mm..lkk",
    "kkl...M..l...ll..M....kM",
    "kM.l..MM........Mm...lkk",
    ".kkl...MMM....MmM...lkM.",
    ".kMkl....mMmMMM....lMkk.",
    "..kkk.l...........lkkk..",
    "...Mkkl..........lkMk...",
    "....kkMll.ll.ll.lMkk....",
    ".....kkkkkk.lMkkkkk.....",
    ".......MkMkkkkkkM.......",
  ],
  // 16×16
  "w_shield_evo": [
    ".......kk.......",
    "......kOOk......",
    "......kOOk......",
    ".....kOOOOk.....",
    "....kOOOOOOk....",
    "....kOyOOyOk....",
    "...kOOOOOOOOk...",
    "...kOOOOOOOOk...",
    "..kOOOOOOOOOOk..",
    "..kOyOOOOOyOk...",
    "..kkkkkkkkkkkk..",
    "..kkkOcOcOkkkk..",
    "..kkOcOcOcOkkk..",
    "....kkkkkkkk....",
    "......krrk......",
    ".......xx.......",
  ],
  // 16×16
  "hero_face_knight": [
    "................",
    ".....kkkkk......",
    "....kKKKKKk.....",
    "...kKKKKKKKk....",
    "...krrrrrrrk....",
    "...kwwwwwwwk....",
    "...kwkwwwkwk....",
    "...kwwwwwwwk....",
    "...kwwkkwwk.....",
    "....kwwwwk......",
    ".....kkkk.......",
    "...kKKKKKKKk....",
    "..kKKKKKKKKKk...",
    ".kKKKKKKKKKKKk..",
    ".kKKKKKKKKKKKk..",
    ".kkkkkkkkkkkkk..",
  ],
  // 16×16
  "hero_face_mage": [
    "................",
    ".......kk.......",
    "......kKKk......",
    ".....kKKKKk.....",
    ".....kKKKKk.....",
    "....kwwwwwwk....",
    "....kwkwwkwk....",
    "....kwwwwwwk....",
    ".....kwwwwk.....",
    ".....kwwwwk.....",
    "......kwwk......",
    "......kwwk......",
    ".....kttttk.....",
    "....kttttttk....",
    "...kttttttttk...",
    "...kkkkkkkkkk...",
  ],
  // 16×16
  "hero_face_ranger": [
    "................",
    ".....kkkkk......",
    "...kkMMMMMkk....",
    ".kkMMMMMMMMMkk..",
    "kkMMMMMMMMMMMkk.",
    "...kwwwwwwwk....",
    "...kwkwwwkwk....",
    "...kwwwwwwwk....",
    "....kwwwwk......",
    ".....kkkk.......",
    "....kKKKKKk.....",
    "...kKKKKKKKk....",
    "..kKKKKKKKKKk...",
    ".kKKKKKKKKKKKk..",
    ".kKKKKKKKKKKKk..",
    ".kkkkkkkkkkkkk..",
  ],
};
